name: Deploy Chrome
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CHROME_APP_ID: ibbnflebibmaomolippckjbahgaophfh
    steps:
    - uses: actions/checkout@v2
    - run: git archive -o package.zip HEAD:src
    - uses: trmcnvn/chrome-addon@v2
      with:
        extension: ${{ env.CHROME_APP_ID }}
        zip: package.zip
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
